stages:
  - deploy
 
deploy:
  stage: deploy
  script:
  - grep '%ver' -P -R -I -l ./src/packagedef | xargs sed -i 's/%ver/'$CI_COMMIT_REF_NAME'/g'
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
  - git push -f heroku master
  - curl https://$HEROKU_APP_NAME.herokuapp.com/status
  artifacts:
    when: on_failure
    paths:
    - .
    expire_in: 1 day
