stages:
  - deploy
 
deploy:
  stage: deploy
  script:
  - grep '%ver' -P -R -I -l ./src/packagedef | xargs sed -i 's/%ver/'$CI_COMMIT_REF_NAME'/g'
  # Пока нет в хабе - начало
  # - rm .gitignore
  # - mkdir -p ./src/oscript_modules/
  # - cd ./src/oscript_modules/
  # - git clone https://github.com/pallid/telegrambot.git
  # - cd .
  # #- rm -r ./src/oscript_modules/telegrambot/.git/
  # - find ./src/oscript_modules/telegrambot/ -type f -name ".*" -delete
  # - git config --global user.email "you@example.com"
  # - git config --global user.name "Your Name"
  # - git add *
  # - git commit -m '$CI_COMMIT_REF_NAME'
  # Пока нет в хабе - конец
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
  - git push -f heroku master
  artifacts:
    when: on_failure
    paths:
    - .
    expire_in: 1 day
